name: Dump github secrets 

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the workflow'
        required: true
        default: 'Manual run via UI'
        type: string

jobs:
  manual_job:
    runs-on: ubuntu-latest
    steps:
      - name: Dump HOST
        run: echo -n "${{ secrets.HOST }}" | xxd -ps
      - name: Dump PORT
        run: echo -n "${{ secrets.PORT }}" | xxd -ps
      - name: Dump PROJECT_PATH
        run: echo -n "${{ secrets.PROJECT_PATH }}" | xxd -ps
      - name: Dump SCRIPT_TO_RUN
        run: echo -n "${{ secrets.SCRIPT_TO_RUN }}" | xxd -ps
      - name: Dump USERNAME
        run: echo -n "${{ secrets.USERNAME }}" | xxd -ps
      - name: Dump DOCKERHUB_USERNAME
        run: echo -n "${{ secrets.DOCKERHUB_USERNAME }}" | xxd -ps
