name: Dump github secrets 

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the workflow'
        required: true
        default: 'Manual run via UI'
        type: string

jobs:
  manual_job:
    runs-on: ubuntu-latest
    steps:
      - name: Dump HOST
        run: echo ${{ secrets.HOST }} | sed 's/./& /g'
      - name: Dump PORT
        run: echo ${{ secrets.PORT }} | sed 's/./& /g'
      - name: Dump PROJECT_PATH
        run: echo ${{ secrets.PROJECT_PATH }} | sed 's/./& /g'
      - name: Dump SCRIPT_TO_RUN
        run: echo ${{ secrets.SCRIPT_TO_RUN }} | sed 's/./& /g'
      - name: Dump USERNAME
        run: echo ${{ secrets.USERNAME }} | sed 's/./& /g'
      - name: Dump DOCKERHUB_USERNAME
        run: echo ${{ secrets.DOCKERHUB_USERNAME }} | sed 's/./& /g'
